college_map = {
    'azst': [
        'arizona state',
        '@SunDevilHoops',
        '@TheSunDevils',
        ' ASU ',
        '@SunDevilWBB',
        'josh christopher'
    ],
    'connecticut': [
        'connecticut',
        ' uconn ',
        '@UConnMBB',
        '@UConnHuskies',
        '@UConnWBB',
        'james bouknight',
        '@jam3s210',
        'sue bird',
        'diana taurasi',
        'tina charles',
        'breanna stewart',
        'napheesa collier',
        'jen rizzotti',
        'gabby williams',
        'kia nurse',
        'aaliyah edwards',
        'stefanie dolson',
        'gavin edwards',
        'niels giffey',
        'roisin upton',
        'Cecile Pieper',
        'stephanie labbe'
    ],
    'duke': [
        ' duke ',
        '@DukeMBB',
        '@dukebasketball',
        '@DukeWBB',
        'jalen johnson',
        '@Jalen_J23'
        'matthew hurt',
        'd.j. steward',
        'dj steward',
        'kara lawson',
        'chelsea gray',
        'oderah chidom',
        'elizabeth balogun',
        'jayson tatum',
        'jahlil okafor',
        'kate van buskirk',
        'madeline price',
        'steven solomon',
        'ashley twichell',
        'celine boutier',
        'leona maguire',
        'jessica springsteen'
    ],
    'florida': [
        'university of florida',
        '@GatorsMBK',
        '@GatorsWBK',
        ' uf ',
        'tre mann',
        '@tre2mann3',
        'scottie lewis',
        'michael holloway',
        'doneisha anderson',
        'lloydricia cameron',
        'yanis david',
        'genevieve lacaze gregson',
        'adriana leon',
        'taylor manson',
        'cory mcgee',
        'marife torres',
        'marija vucenovic',
        'andres arroyo',
        'bradley beal',
        'will claye',
        'marquis dendy',
        'joseph fahnbulleh',
        'caeleb dressel',
        'bobby finke',
        'brett fraser',
        'grant holloway',
        'mark kolozsvary',
        'eddie lovett',
        'hakim sani brown',
        'kieran smith'
    ],
    'fsu': [
        ' fsu ',
        'florida state',
        'florida state university',
        '@FSUHoops',
        '@Seminoles',
        '@fsuwbb',
        'scottie barnes',
        '@ScottBarnes561',
        'raiquan gray',
        '@Tgray4',
        'm.j. walker',
        'mj walker',
        'koprivica',
        'zak seddon',
        'kimmy williams',
        'linden hall',
        'istvan szogi',
        'alonzo russell',
        'kevin borlee',
        'jonathan borlee',
        'anne zagre',
        'susan krumins',
        'andrew coscoran',
        'kemar hyman',
        'mulern jean',
        'leonor rodrgiuez',
        'maria conde',
        'katrina young',
        'matilda castren',
        'kim metraux',
        'izaak bastian',
        'julio horrego',
        'ida hulkko',
        'emir muratovic',
        'nick lucena',
        'jason lochhead',
        'luke loucks'
    ],
    'georgia': [
        'university of georgia',
        '@UGABasketball',
        'denzel comenentia',
        'johannes erm',
        'elija godwin',
        'cejhae green',
        'charles grethen',
        'lynna irby',
        'morgann leleux',
        'freida lim',
        'shaunae miller-uibo',
        'jasmine moore',
        'keturah orji',
        'ellen perez',
        'chanice porter',
        'garrett scantling',
        'levern spencer',
        'sepp straka',
        'karel tilga',
        'maicel uibo',
        'jarryd wallace',
        'kendell williams',
        'jack bauerle',
        'dan laak',
        'mike mobley'
    ],
    'illinois': [
        'university of illinois',
        '@IlliniMBB',
        '@IlliniWBB',
        'ayo dosunmu',
        '@AyoDos_11',
        'michelle bartsch-hackley',
        'tyson bull',
        'thomas detry',
        'alex diab',
        'david kendziera',
        'thomas pieters',
        'jordyn poulter',
        'rajeev ram',
        'erin virtue'
    ],
    'kansas': [
        'kansas university',
        '@KUHoops',
        '@KUWBball',
        'mason finley',
        'bryce hoppel',
        'gleb dudarev',
        'alexandria emilianov',
        'christina clemons',
        'stanley redwine',
        'andy kokhanovsky',
        'michael whittlesey'
    ],
    'lsu': [
        ' lsu ',
        'louisiana state',
        '@LSUBasketball',
        '@LSUsports',
        '@LSUwbkb',
        'cameron thomas',
        '@24_camthomas',
        'cam thomas',
        'trendon watford',
        'javonte smart',
        'brooks curry',
        'sylvia fowles',
        'michael cherry',
        'vernon norwood',
        'juvaughn harrison',
        'aleia hobbs',
        'anne tuxen',
        'juan celaya-hernandez',
        'favour ofili',
        'allysha chapman',
        'amanda sanchez',
        'mondo duplantis',
        'glenn hardin',
        'kelly-ann baptiste',
        'semoy hackett',
        'akanni hislop',
        'michael venus',
        'neal skupski',
        'marcus daniell',
        'madelene sagstrom',
        'duop reath'
    ],
    'miami': [
        'university of miami',
        '@CanesHoops',
        '@MiamiHurricanes',
        '@CanesWBB',
        'danny valencia',
        'ben wanger',
        'emma gullstrand',
        'daniela darquea',
        'murielle ahoure',
        'ebony morrison',
        'alysha newman',
        'kristina knott'
    ],
    'michigan': [
        'university of michigan',
        '@umichbball',
        '@umichwbball',
        'franz wagner',
        '@franzboogie',
        'myles amine',
        'patrick callan',
        'maggie macneil',
        'jayde riviere',
        'ekpe udoh',
        'moritz wagner',
        'mike woods',
        'michael hixon',
        'mike hilde',
        'uche eke',
        'sam mikulak',
        'cameron bock',
        'jayde riviere',
        'shelina zadorsky',
        'steven bastien',
        'mason ferlic',
        'nick willis',
        'tiffany porter',
        'cindy sember',
        'jeff porter',
        'val barthelemy',
        'erin virtue',
        'abby andrews',
        'amy ridge',
        'stevan micic',
        'sean bormet'
    ],
    'ohiostate': [
        'ohio state',
        '@OhioStateHoops',
        '@OhioStAthletics',
        'duane washington',
        '@dwizthekid4',
        'adelaide aquilla',
        'anavia battle',
        'christine clemons',
        'kyle snyder',
        'alec yoder',
        'emily armstrong',
        'nichelle prince',
        'misha koudinov',
        'maggie barrie',
        'eric harrison'
    ],
    'northcarolina': [
        'university of north carolina',
        '@UNC_Basketball',
        '@GoHeels',
        'day-ron sharpe',
        'dayron sharpe',
        '@dayron_sharpe',
        'tim federowicz',
        'ryder ryan',
        'aranza vazquez',
        'anton down-jenkins',
        'yaidel gamboa',
        'crystal dunn',
        'tobin heath',
        'katie bowen',
        'lotte wubben-moy',
        'lucy bronze',
        'kenny selmon'
    ],
    'notredame': [
        'notre dame',
        '@NDmbb',
        '@ndwbb',
        'molly seidel',
        'yared nuguse',
        'natalie achonwa',
        'jewell loyd',
        'skylar diggins-smith',
        'angie akers',
        'jackie young'
    ],
    'texas': [
        'university of texas',
        '@TexasMBB',
        '@TexasLonghorns',
        '@TexasWBB',
        'kai jones',
        '@242_jones',
        'jericho sims',
        'greg brown',
        'ryan crouser',
        'teahna daniels',
        'tara davis',
        'steffin mccarter',
        'jordan windle',
        'hailey hernandez',
        'kevin durant',
        'ariel atkins',
        'chiaka ogbogu',
        'cat osterman'
    ],
    'virginia': [
        'university of virginia',
        '@UVAMensHoops',
        '@VirginiaSports',
        '@UVAWomensHoops',
        'trey murphy',
        '@Treymurphyiii',
        'sam hauser',
        'jay huff',
        'dawn staley',
        'aisha mohammed balarabe',
        'mike tobey',
        'francisco caffaro',
        'becky sauerbrunn',
        'emily sonnett',
        'joe bell',
        'filip mihaljević',
        'michaela meyer'
    ],
    'wisconsin': [
        'wisconsin',
        '@BadgerMBB',
        '@UWBadgers',
        '@BadgerWBB',
        'd’mitrik trice',
        'mitrik trice',
        '@DMitrikTrice0',
        'jrue holiday',
        'khris middleton',
        'stephanie roble',
        'madelynn bernau',
        'phoebe bacon',
        'yigit aslan',
        'lauren carlini',
        'rose lavelle'
    ]
}
